In [1]:
import numpy as np

In [2]:
c = np.array([10,20,30])
d = np.array([5,10,15,20])
e = np.array([12])

In [3]:
np.tile(c,(5,1)) # forms an mxn matrix with the given array

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [4]:
c+d.reshape(4,1)

array([[15, 25, 35],
       [20, 30, 40],
       [25, 35, 45],
       [30, 40, 50]])

In [5]:
np.tile(d.reshape(4,1),(1,3))

array([[ 5,  5,  5],
       [10, 10, 10],
       [15, 15, 15],
       [20, 20, 20]])

# Trying the Broadcasting myself

In [6]:
c = np.linspace(0,7,8).reshape((2,4))
c

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

When an array operation is performed in combination with a single value, numpy
duplicates the singleton to create an array the same size as the array so the operation is
successfully completed.

In [7]:
c + 2 # Adds 2 to everyelement in c

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

c + np.array([1,2,3]) 
ValueError: operands could not be broadcast together with shapes (2,4) (3,)
    This is because of difference in the dimension

In [8]:
c + np.array([1,2,3,4]) # Adds the new array to the first row of the arry, c

array([[ 1.,  3.,  5.,  7.],
       [ 5.,  7.,  9., 11.]])