In [109]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [4]:
# Question 1
a = 2 + 5 % 12 * 15 // 2**3
print(a)

11


In [142]:
# Question 2
d = 70
if d > 55:
    print('d'+' is large')

d is large


In [112]:
# Question 3
x = list(range(1,9,2)) 
print(x)

[1, 3, 5, 7]


In [146]:
# Question 4
a = 'this is python'
a = a.split()
a = [i.capitalize() if i != 'is' else i for i in a]
print('-'.join(a))

This-is-Python


In [114]:
# Question 5
x = 2
for i in range(3):
    x/2
print(x)

2


In [115]:
# Question 6
x= linspace(0,12,3)
y = x**2
print(y)

[  0.  36. 144.]


In [116]:
# Question 7
a = list(range(5,0))
print(a)

[]


In [117]:
# Question 8
x = [3,2,6,9,1,4,0]
val = 0
loc = 0
for i in range(len(x)):
    if x[i] > val:
        val = x[i]
        loc = i 
print(loc)

3


In [118]:
# Question 9
F = [0,1]
for i in range(5):
    F.append(F[-2]+F[-1])
print(F)

[0, 1, 1, 2, 3, 5, 8]


In [119]:
# Question 10
x = linspace(0,1,6)
y = (3*x + 1).astype(int)
print(y)

[1 1 2 2 3 4]


In [120]:
# Question 11
F = [0,1]
for i in range(5):
    F.append(F[-2]+F[-1])
s = 0
for i in range(3):
    s += F[2*i+1]
print(s)

8


In [121]:
# Question 12
a = [0,1,2,3,4,5,6,7,8,9,10,11,12]
print(a[::3])

[0, 3, 6, 9, 12]


In [122]:
# Question 13
vals = []
for i in range(2,5):
    for j in range(i+1,5):
        res = sqrt(i**2 + j**2)
        if res == int(res):
            vals.append([i,j])
print(vals)


[[3, 4]]


In [123]:
# Question 14
S ="hello"
print(S*3)

hellohellohello


In [124]:
# Question 15
x = 1
for i in range(5):
    x /= 2 
print(x)

0.03125


In [125]:
# Question 16
a = 'I am taking game theory'.split()
b = [0,1,1,0,2]
res = [a[i][b[i]] for i in range(5)]
print("".join(res))

Image


In [126]:
# Question 17
x = linspace(0,5,6,dtype=int)
y = zeros_like(x)
y[x]= x[x]/2
print(y)

[0 0 1 1 2 2]


In [127]:
# Question 18
p = [2,3]
for i in range(4,9):
    if list(filter(lambda x: i%x == 0, p)) == []:
        p.append(i)
print(p)

[2, 3, 5, 7]


In [128]:
p = [2,3]
for i in range(4,9):
    if list(filter(lambda x: i%x == 0, p))==[]:
        p.append(i)
print(p)

[2, 3, 5, 7]


In [129]:
# Question 19
nums = [1,2,1,3,4,6,4,1,2,2,1]
count = {}
while len(nums)>0:
    val = nums[0]
    i= nums.count(val)
    count[val]= i
    for j in range(i):
        del nums[nums.index(val)]
print(count)

{1: 4, 2: 3, 3: 1, 4: 2, 6: 1}


In [130]:
# Question 20
a = range(2,6,0.1)
print(liSt(a))

TypeError: 'float' object cannot be interpreted as an integer

In [131]:
c={1:2,2:3}
type(c)
c[2]

3

##### Section B: In the following questions, running the code as it is results in an error. The code will run perfectly if two lines of code are interchanged. Write the line numbers of the two lines that should be interchanged for the code to run.

In [132]:
a=(1,2,3,4,5,6,7)
a[-1] = 8 
a = list(a)
print(a)

TypeError: 'tuple' object does not support item assignment

In [133]:
# We have to swap lines 2 and 3
a=(1,2,3,4,5,6,7) 
a = list(a)
a[-1] = 8
print(a)

[1, 2, 3, 4, 5, 6, 8]


In [134]:
a = [-2,-1,0,1,2]
b = []
for i in a:
    b.append(1/i)
    if i == 0:
        continue 
    
print(b)

ZeroDivisionError: division by zero

In [135]:
# We have to swap lines 4 and 7
a = [-2,-1,0,1,2]
b = []
for i in a:
   
    if i == 0:
        continue 
    b.append(1/i)
print(b)

[-0.5, -1.0, 1.0, 0.5]


In [136]:
x= [2,4,6,8,10]
x = array(x) 
x.append(12) 
y = (x-1)**2 
print(y)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [137]:
# WE have to swao lines 2 and 3
x= [2,4,6,8,10] 
x.append(12) 
x = array(x)
y = (x-1)**2 
print(y)

[  1   9  25  49  81 121]


In [139]:
c = 'Here are some python codes'
p_loc = c.find('python')
c[p_loc] = 'P'
c = list(c) 
c = ''.join(c)
print(c)

TypeError: 'str' object does not support item assignment

In [140]:
# We have swap lines 3 and 4
c = 'Here are some python codes'
p_loc = c.find('python')
c = list(c) 
c[p_loc] = 'P'
c = ''.join(c)
print(c)

Here are some Python codes


In [141]:
c = [1,2,3,4,5,6]
cumsum = [1]
while i < len(c):
    i = 1
    cumsum.append(c[i]+cumsum[-1]) 
    i += 1 
print(cumsum)

KeyboardInterrupt: 

In [105]:
# We have to swap lines 3 and 4
c = [1,2,3,4,5,6]
cumsum = [1]
i = 1
while i < len(c):
    cumsum.append(c[i]+cumsum[-1]) 
    i += 1 
print(cumsum)

[1, 3, 6, 10, 15, 21]
