### COMPLEX

In [5]:
myval = complex(1,3)

In [6]:
props = {"Real":myval.real,"Imaginary":myval.imag,"Conjugate":myval.conjugate(), "Magnitude":abs(myval)}

In [7]:
print(props)

{'Real': 1.0, 'Imaginary': 3.0, 'Conjugate': (1-3j), 'Magnitude': 3.1622776601683795}


### Example
Write python code that finds the roots of the quadratic equation ax2 + bx + c where
a = 1; b = 5; c = 6

In [10]:
a = 1
b = 5
c = 6
D = b**2-4*a*c
x_1 = (-b-D**0.5)/(2*a)
x_2 = (-b+D**0.5)/(2*a)

roots = {"x1":x_1, "X2":x_2}
print(roots)

{'x1': -3.0, 'X2': -2.0}


### FUNCTIONS
def function_name(arg_list):
  function_code 1
  function_code 2
  ....
  function_code n
  return output

#### Write a function that returns the roots of a quadratic equation

In [11]:
def quadratic_roots(a,b,c):
    D = b**2-4*a*c
    X1 = -b-D**0.5
    X2 = -b+D**0.5
    return(X1,X2)

solve
$3x^2+9x+6$

In [12]:
quadratic_roots(3,9,6)

(-12.0, -6.0)

### USING FUNCTIONS

In [13]:
import math

In [15]:
from math import sin, cos, tan

In [16]:
sin(2)

0.9092974268256817

In algebra you learnt about the nth roots of unity, defined as

$$z_{i} = \cos(\frac{2k\pi}{n}) + i\sin(\frac{2k\pi}{n})\ \; k = 0,1,2,...,n-1$$

Write code to find the values of the 5th roots of unity.

In [38]:
def unity(n):
    from math import cos, sin, pi
    for k in range(0,n):
        zi = complex(cos(2*k*pi/n),sin(2*k*pi/n))
        print(zi)     

In [45]:
unity(5)

(1+0j)
(0.30901699437494745+0.9510565162951535j)
(-0.8090169943749473+0.5877852522924732j)
(-0.8090169943749475-0.587785252292473j)
(0.30901699437494723-0.9510565162951536j)


Consider the list stored in the variable stud_list with 20 elements:
Which elements will be returned by the code stud_list[2:15:4]
Which elements will be returned by the code stud_list[10:1]
Which elements will be returned by the code stud_list[12:1:-3]
Which elements will be returned by the code stud_list[::-1]
Which elements will be returned by the code stud_list[2::4]
Which elements will be returned by the code stud_list[:15:4]
How can the elements in index positions 5, 8, 11, 14 be extracted?

In [63]:
study_lilst = list(range(1,21))
study_lilst[2:15:4] # start at 2+1, to 15 step of 4
study_lilst[10:1] # nnothing
study_lilst[12:1:-3]
study_lilst[::-1]
study_lilst[2::4]
study_lilst[:15:4]
study_lilst[4,7,10,13]

TypeError: list indices must be integers or slices, not tuple

In [62]:
print(study_lilst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


### LIST

In [64]:
a = [1,2,3,4,5,6,7,8,9]
b = a
b.append(10)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


a = [1,2,3,4,1,1,5,2,4]
#Find the first occurence on 1 beginning from index 0
print({’count’:a.count(1),’index’:a.index(1)})
#Find the first occurence on 1 beginning from index 1
print({’count’:a.count(1),’index’:a.index(1,1)})
a = [1,2,3,4,1,1,5,2,4]
#Find the first occurence on 1 beginning from index

In [7]:
a = [1,2,3,4,1,1,5,2,4]
print(a.count(1))
a.index(1)
print({"count":a.count(1),"index":a.index(1,1)})

len(a)
a[9]

3
{'count': 3, 'index': 4}


IndexError: list index out of range

In [9]:
a = [1,2,3,4,1,1,5,2,5]

In [11]:
b = (1,2,3,4,1,1,5,2,5)

In [13]:
print(8 in a)

False


In [15]:
print(2 in b)

True


In [17]:
a = [1,2,3,4,5,6]
b = ['a','b','c']

In [19]:
a+b

[1, 2, 3, 4, 5, 6, 'a', 'b', 'c']

In [20]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [21]:
a*5

[1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6]

In [22]:
5*a

[1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 4,
 5,
 6]

a = ’This is a Python string’
2 print(a.upper())
3 print(a.lower())
4 print(’P is located at index ’+str(a.index(’P’)))
5 print(a.replace(’Python’,’Cython’))
6 print(’endswith the text String? ’+ str(a.endswith(’String’)))
7 print(’endswith the text string? ’+ str(a.endswith(’string’)))

In [23]:
a = 'This is a Python string'

In [24]:
print('P is located at index '+str(a.index('P')))

P is located at index 10


In [26]:
print('Ends with the word String? '+str(a.endswith('String')))

Ends with the word String? False


In [27]:
print('Ends with the word string? '+str(a.endswith('string')))

Ends with the word string? True


Consider the mathematical structure with the coordinates (1:0; 0:0); (3:0; 5:2);
(􀀀0:5; 0:87); (􀀀6:0; 0:0); (􀀀0:5;􀀀0:87); (3:0;􀀀5:2): Write python code to find the
circumference of the structure. How would you extend it if your structure has many
points.

In [38]:
def circumference(x,y):
    from math import sqrt
    D = 0.00
    for i in range(1,len(x)):
        di = sqrt((x[i]-x[i-1])**2 + (y[i]-y[i-1])**2)
        D += di
    return(D)

In [39]:
circumference(x = [1,2,3,4,5], y = [10,11,12,13,14])

5.656854249492381

a = [1,2,3,4,5,6,7,8,9,10]
2 a_split = [[],[]]
3 for i in a:
4 a_split[i%2].append(i)
5
6 print("Even numbers are "+str(a_split[0]))
7 print("Odd numbers are "+str(a_split[1]))

In [50]:
a = [1,2,3,4,5,6,7,8,9,10]
a_split = [[],[]]
for i in a:
    a_split[i%2].append(i)

In [51]:
a_split[0]

[2, 4, 6, 8, 10]

In [75]:
a = 'Nurses run'
b = a.replace(' ','')
b

'Nursesrun'

In [87]:
def palindrome(Word):
    word = Word.replace(' ','')
    word = word.lower()
    print('Is '+str(Word)+' a palindrome? '+str(word[::1]==word[::-1]))

In [88]:
palindrome('Nurses run')

Is Nurses run a palindrome? True


In [90]:
palindrome("Dammit Im Mad")

Is Dammit Im Mad a palindrome? True


In [91]:
30000/500


60.0

In [87]:
25%2

1

In [208]:
def binary(n):
    whole = []
    frac = []
    while n>0:
        frac.append(n%2)
        n = n//2
        whole.append(n)
    frac = frac[::-1]
    res = ''
    for i in range(len(frac)):
        res += str(frac[i])
    return(res)
    

In [209]:
binary(25)

'11001'

In [214]:
def unit_vector(a,d,t):
    unit = [[],[]]
    unit[0] = a[0]+t*d[0]
    unit[1] = a[1]+t*d[1]
    print(unit)

unit_vector([2,1],[2,2],2)

[6, 5]


In [222]:
def cross_prod(x,y):
    from math import acos,sqrt
    x_dot_y = x[0]*y[0]+x[1]*y[1]
    mag_x = sqrt((x[0])**2 + (x[1])**2)
    mag_y = sqrt((y[0])**2 + (y[1])**2)
    mag_prod = mag_x*mag_y
    res = acos(x_dot_y*mag_prod)
    print(res)
cross_prod([4,3],[5,12])

ValueError: math domain error

In [228]:
5*13
from math import acos
acos(1)

0.0

In [233]:
def sign_change(x):
    bool = []
    for i in range(len(x)):
        bool.append(x[i]>=0)
    check = sum(bool)!=len(x)
    res = "has the sign changed? "+str(check)
    return(res)
sign_change([1,1,1,1])



'has the sign changed? False'

In [236]:
a = [1,2,3,4,5,6,7,8,9]
i = 0
pow = []

while i < len(a):
    val = 10**-a[i]
    if val <0.001:
        break
    pow.append(val)

    i += 1

pow

[0.1, 0.01, 0.001]

In [237]:
a = [1,2,3,4,5,6,7,8,9]
i = 0
pow = []

while i < len(a):
    val = 10**-a[i]
    if val <0.001:
        continue
    pow.append(val)

    i += 1

pow

KeyboardInterrupt: 

In [251]:
a = [2,3,4,5,6,7,8,9]
i = 0
roots = []
from math import sqrt
while i < len(a):
    val = sqrt(a[i])
    if val % 1 ==0.0:
        break
    roots.append(val)
    i +=1
roots


[1.4142135623730951, 1.7320508075688772]

In [258]:
X = [-1,0,1,2,3]
[3*x**2-5*x+6 for x in X]
from math import sin
[sin(x)/x for x in X if x!=0]
[sin(x)/x if x!=0 else 1 for x in X]

[0.8414709848078965,
 1,
 0.8414709848078965,
 0.45464871341284085,
 0.0470400026866224]

In [261]:
X = [-1,0,1,2,3]
A = lambda x:3*x**2
(lambda x:3*x**2)(2)

12

In [270]:
map(sum,[1,2,3,4])

In [2]:
a = [1,2,3,4,5]
sum(a)

15

In [22]:
from math import sqrt
list(map(sqrt,a))
list(filter(lambda x:sqrt(x)>1,a))

[2, 3, 4, 5]

In [3]:
import functools
functools.reduce(max,a)

5

In [1]:
import numpy as np

In [13]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [14]:
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [20]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
a.shape
a.dtype

dtype('float64')

In [30]:
a.reshape(-1,5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [31]:
a.astype('complex')

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j])

In [32]:
a.size

10

In [33]:
a.reshape(5,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [36]:
a[2:4]

array([3., 4.])

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
%pylab inline

ModuleNotFoundError: No module named 'matplotlib'

In [3]:
42%5

2

In [68]:
Z = 2+1

In [1]:
stri = '	Analysis of Employment and Economic Activity in Ghana: Identifying Growth Drivers and Challenges'

In [3]:
stri.upper()

'\uf0d8\tANALYSIS OF EMPLOYMENT AND ECONOMIC ACTIVITY IN GHANA: IDENTIFYING GROWTH DRIVERS AND CHALLENGES'

In [63]:
1A = 2+1

SyntaxError: invalid decimal literal (4085842427.py, line 1)

In [65]:
_A = 1+2

In [76]:
myint = int(12)
myfloat = float(12.0)
myccomplex = complex(2,3)
myccomplex
mybool = True
mybool+1

2

In [207]:
mytext = '0cat'
str(mybool+1)
int(mytext[0])

0

In [98]:
mylist = [1,2,3,4,5,'cat']
mylist
mytuple = (1,2,3,4.5)


list(range(10))
list(range(1,10))
list(range(1,10,2))
list(range(0,10,2))

list(range(10,1,-2))
print(range(10))

range(0, 10)


In [204]:
mydict = {'Name':'Yaw','age':20,'Height':150,'dark':True}
mydict

mynone = None
mynone

mydict['age']

20

In [111]:
2+5 # addition
2-7 #subtraction
2*5 # multiplication
5/2 #division
5//2 # floor division
5%2 #modulus
5**2 #exponent

25

In [114]:
2+5-9/(3*2)

5.5

In [124]:
x = 5
x
x /= 2
x

2.5

In [134]:
23==25
23 != 25
23 < 25
23 > 25
23 <= 25
25 > 25

False

In [142]:
mycomp = complex(3,2)
mycomp
mycomp.conjugate()
abs(mycomp)==13**0.5

True

write a code to find the roots of:
$$ax^2+bx+c \ ;\ given\ the\ values\ of\ a,b,c $$

In [143]:
def quad_roots(a,b,c):
    D = b**2-4*a*c
    X1 = (-b-D**0.5)/(2*a)
    X2 = (-b+D**0.5)/(2*a)
    roots = {'X1':X1,'X2':X2}
    return(roots)

In [146]:
quad_roots(1,5,6)
quad_roots(4,2,4)

{'X1': (-0.25000000000000006-0.9682458365518543j),
 'X2': (-0.24999999999999994+0.9682458365518543j)}

In [154]:
import math
math.sqrt(25)

import  math as m
m.sqrt(25)

from math import cos,sin, sqrt

In [155]:
cos(1)

0.5403023058681398

In algebra, the nth root of unity is defined as
$$z_{i}= \cos(\frac{2 \pi k}{n}) + i \sin(\frac{2 \pi k}{n}) \ \ k = 0,1,2,...,n-1 $$

write a code to find the nth roots of unity

In [161]:
def comp_roots(n):
    from math import cos,sin,pi
    for k in range(0,n,1):
        zi= complex(cos((2*pi*k)/n),sin((2*pi*k)/n))
        print(zi)


In [164]:
comp_roots(1)

(1+0j)


In [ ]:
def complex_roots(n):
    from math import cos,sin,pi
    

In [165]:
def rad_circle(A):
    from math import pi
    D= (A/pi)
    r = D**0.5
    return(r)



In [166]:
rad_circle(300)

9.772050238058398

In [168]:
def radI_circle(A):
    from math import pi,sqrt
    r = (A/pi)**0.5
    return(r)
    

In [169]:
radI_circle(300)

9.772050238058398

In [282]:
mystr = None

In [283]:
type(mystr)

NoneType

In [285]:
list(range(5,10,-1))

[]

In [318]:
mylist = [1,2,3,4,2,6,2,8,9,10,11,2,13,14,15,16]
mylist[::3]
mytuple = [1,2,3,45,5678]
mylist.index(2,7,16)

11

In [300]:
mylist.append(21)
mylist
mylist.extend(mytuple)

In [301]:
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 21, 1, 2, 3, 45, 5678]

In [302]:
freda = [1,2,3]

In [319]:
freda+mytuple

[1, 2, 3, 1, 2, 3, 45, 5678]

In [330]:
mystr = 'Freda and Sylvia are 2 Gays'
mystr.isalnum()
a = str(1)
a.isalnum()
mystr.index('S')
mystr.find('s')
mystr.count('s')
mystr.replace('2','two')
mystr.upper()

'FREDA AND SYLVIA ARE 2 GAYS'

In [337]:
a = (1,0)
b = (3,5.2)
c = (-0.5,0.87)
d = (-6,0)
e =(-0.5,-0.87)
f = (3,-5.2)
from math import sqrt
AB = sqrt((b[0]-a[0])**2 + (b[1]-a[1])**2)
BC = sqrt((c[0]-b[0])**2 + (c[1]-b[1])**2)
CD= sqrt((d[0]-c[0])**2 + (d[1]-c[1])**2)
DE= sqrt((e[0]-d[0])**2 + (e[1]-d[1])**2)
EF = sqrt((f[0]-e[0])**2 + (f[1]-e[1])**2)
FA= sqrt((a[0]-f[0])**2 + (a[1]-f[1])**2)
circum = AB+BC+CD+DE+EF+FA
circum

33.41480971311444

In [341]:
def circumf(a,b,c,d,e,f):
    from math import sqrt
    AB = sqrt((b[0]-a[0])**2 + (b[1]-a[1])**2)
    BC = sqrt((c[0]-b[0])**2 + (c[1]-b[1])**2)
    CD= sqrt((d[0]-c[0])**2 + (d[1]-c[1])**2)
    DE= sqrt((e[0]-d[0])**2 + (e[1]-d[1])**2)
    EF = sqrt((f[0]-e[0])**2 + (f[1]-e[1])**2)
    FA= sqrt((a[0]-f[0])**2 + (a[1]-f[1])**2)
    circum = AB+BC+CD+DE+EF+FA
    return(circum)

In [340]:
circumf(a,b,c,d,e,f)

33.41480971311444

In [342]:
X = [10,20,30,40,50]
Y = [0,1,2,3,4]
Z = []
for i in range(len(X)):
    Z.append(X[i]/2)
print(Z)

[5.0, 10.0, 15.0, 20.0, 25.0]


Write a code that finds the square root of the integers from -5 to 5

In [ ]:
X = list(range(0,6))
Z =[]
from math import sqrt
for i in range(len(X)):
    val = sqrt(X[i])
    Z.append(val)
print(Z)



[0.0, 1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


In [355]:
sqrt(4)

2.0

A palindrome is a word, phrase, or sequence that reads the same backwards as
forwards, e.g. madam or nurses run. Write python code to test if a string is a
palindrome

In [372]:
def pale(txt):
    mystr =txt.replace(' ','')
    mystr =mystr.lower()
    result = mystr[::-1] == mystr
    print('is '+str(txt)+' a palindrome? '+str(result))
    



In [377]:
pale('madam')
pale('Nurses RuN')
pale('coconut')
pale('coccaine')

is madam a palindrome? True
is Nurses RuN a palindrome? True
is coconut a palindrome? False
is coccaine a palindrome? False


In [366]:
text = 'Nurses run'
text_edt = text.replace(' ','')
text_edt == text_edt[::-1]

False

In [1]:
t = 'Tetteh'
t.replace('t','s')

'Tesseh'

In [ ]:
A = [1,2,3,4,5]
B = []
for i in range(len(A)):
    a = A[i]**2
    print(a)

1
4
9
16
25


In [5]:
A = [1,2,3,4,5]
B = []
for i in range(len(A)):
    a = A[i]**2
print(a)

25


In [7]:
A = [1,2,3,4,5]
B = []
for i in range(len(A)):
    a = A[i]**2
    B.append(a)
print(B)

[1, 4, 9, 16, 25]


In [8]:
A = [1,2,3,4,5]
B = []
for i in range(len(A)):
    a = A[i]**2
    B.append(a)
    print(B)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]


Write a code to check the first 10 integers if they are even and print the even ones

In [ ]:
nums = [1,2,3,4,5,6,7,8,9,10]
even = []
for i in range(1,len(nums)+1):
    k = i-1
    while nums[k]%2==0:
        even.append(nums[k])
        k += 1
print(even)        

[2, 4, 6, 8]


In [ ]:
A = [1,2,3,4,5,6,7,8,9,10]
B = [[],[]]
C = []
D = []
for i in range(len(A)):
    x = A[i]%2 == 0
    y = A[i]%2 != 0
    C.append(x)
    D.append(y)
    for i in range(len(C)):
        C[i]

print(D)



[True, False, True, False, True, False, True, False, True, False]


In [27]:
A = [1,2,3,4,5,6,7,8,9,10]
B = [[],[]]
for i in range(len(A)):
    x = A[i]%2 == 0
    B[x]=A[i]
    print(B)


[1, []]
[1, 2]
[3, 2]
[3, 4]
[5, 4]
[5, 6]
[7, 6]
[7, 8]
[9, 8]
[9, 10]


In [29]:
C = [[],[]]
C[0]=True
C

[True, []]

In [ ]:
x = 1
res = []
while x <=5:
    res.append(x**0.5)
    x += 1
print(res)

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


In [ ]:
x = 1
odd = []
while x%2 != 0 x<10: 


write a code to print the even numbers from 1 to 10

In [58]:
nums[-1]

10

write a code to print the first 5 multiples of 5

In [43]:
x = 0
multiples = []
while x< 5*5:
    multiples.append(x)
    x+=5
print(multiples)


[0, 5, 10, 15, 20]


In [63]:
x = list(range(-1,4))
fx = []
for i in range(-10,10):
    if i in x:
        f_x = 3*x[i]**2-5*x[i]+6
        fx.append(f_x)
print(fx)

[18, 14, 6, 4, 8]


$\in$

In [71]:
def quad_cond(x):
    if x in range(-1,4):
        f_x = 3*x**2-5*x+6
    else:
        f_x = "out of range"
    return(f_x)

In [72]:
quad_cond(-4)

'out of range'

In [73]:
from math import sin
sin(-1)/-1

0.8414709848078965

In [76]:
fx = lambda x: 3*x**2-5*x+6

In [75]:
(lambda x: 3*x**2-5*x+6)(1)

4

In [77]:
fx(1)

4

In [78]:
[3*x**2-5*x+6 for x in [-1,0,1,2,3]]

[14, 6, 4, 8, 18]

In [79]:
[3*x**2-5*x+6 for x in [-1,0,1,2,3] if x>0]

[4, 8, 18]

In [ ]:
[3*x**2-5*x+6 for x in [-1,0,1,2,3] if x>0]

In [82]:
from math import sqrt
list(map(sqrt,(1,2,3,4,5)))

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

In [85]:
list(filter(lambda x:x%2==0,[1,2,3,4,5,6,7,8,9,10]))

[2, 4, 6, 8, 10]

In [86]:
from functools import reduce
reduce(max,[2,1,3,4,6,17,14,89])

89