# MATRIX OPERATIONS

## 1. Identity Matrix

In [1]:
import numpy as np
np.eye(4) # 4x4 Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2. Two dimensional matrices

In [3]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 3.Matrix multiplication

In [5]:
a = 2*np.eye(4)
b = np.array([1,2,3,4])
c=b.reshape((4,1))

In [6]:
np.dot(a,c)

array([[2.],
       [4.],
       [6.],
       [8.]])

In [7]:
np.dot(b,a)

array([2., 4., 6., 8.])

In [12]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
A = np.array([[1,2,3,4],[2,1,1,0],[1,1,5,2]])

In [14]:
B=np.array([[1,2],[0,1],[1,1],[3,1]])

In [15]:
np.dot(A,B)

array([[16, 11],
       [ 3,  6],
       [12, 10]])

In [16]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
import numpy.linalg as linlalg # For linear algebra