In [2]:
import numpy as np

In [7]:
import google.generative as genai

ModuleNotFoundError: No module named 'google.generative'

In [8]:
a=[1,2,3,4,5,6,7,8,9]

In [2]:
import math

In [11]:
math.cos(90)
math.sin(math.radians(90))

1.0

In [15]:
math.sin(0)

0.0

$$\Lambda$$

$$\Phi$$

$$\psi \Psi \chi \Chi$$

In [ ]:
a1 = np.array(a)

In [ ]:
a1

In [ ]:
a1**2

In [ ]:
np.sin(a)

In [ ]:
import math
n = 5
res = []
for i in range(n):
    res.append(math.cos(2*math.pi*i/n)+1j*math.sin(2*math.pi*i/n))
res    

In [ ]:
list(range(0,9,2))

In [ ]:
np.arange(0,20.1,0.2)

In [ ]:
a=np.arange(0,12.1,(12/23))
a
# np.arange(start inclusive, stop exclusive, step including float)

In [ ]:
len(a)
# Number of elements in a

In [ ]:
np.linspace(0,12,24)
# np.linspace(start inclusive, stop inclusive, number of elements)

In [ ]:
np.zeros(5)
# An array with five zeros as the elements

In [ ]:
np.ones(5)
# An array with five ones as the elements

In [ ]:
np.ones(10)*15
# An array with five ones as the elements nd each of the elements are multiplied by 15

In [3]:
np.linspace(15,15,10)

array([15., 15., 15., 15., 15., 15., 15., 15., 15., 15.])

In [ ]:
np.zeros(10)+10

In [4]:
np.empty(20)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609111e-307,
       7.56556349e-307, 7.56599807e-307, 7.56595054e-307, 6.23059386e-307,
       1.60218763e-306, 1.29060871e-306, 9.34593493e-307, 6.23059726e-307,
       6.23060405e-307, 6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
       9.34600963e-307, 1.86921143e-306, 6.23061763e-307, 1.60220393e-306])

In [5]:
np.empty(10)

array([15., 15., 15., 15., 15., 15., 15., 15., 15., 15.])

In [6]:
np.empty(24)*10

array([6.23042070e-306, 4.67296746e-306, 1.69121096e-305, 9.34609111e-306,
       7.56556349e-306, 7.56599807e-306, 7.56595054e-306, 6.23059386e-306,
       1.60218763e-305, 1.29060871e-305, 9.34593493e-306, 6.23059726e-306,
       6.23060405e-306, 6.23053954e-306, 9.34609790e-306, 8.45593934e-306,
       9.34600963e-306, 1.86921143e-305, 6.23061763e-306, 1.60220800e-305,
       7.56589622e-306, 1.11260144e-305, 8.34449806e-307, 1.24604136e-305])

In [7]:
np.empty(30)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609111e-307,
       7.56556349e-307, 7.56599807e-307, 7.56595054e-307, 6.23059386e-307,
       1.60218763e-306, 1.29060871e-306, 9.34593493e-307, 6.23059726e-307,
       6.23060405e-307, 6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
       9.34600963e-307, 1.86921143e-306, 6.23061763e-307, 6.23053954e-307,
       2.22522597e-306, 1.06810268e-306, 6.23052935e-307, 1.78019082e-306,
       1.86921279e-306, 8.34445562e-308, 1.78022342e-306, 8.06635958e-308,
       8.34424342e-308, 2.10081501e-312])

In [8]:
np.ones(500)*4*np.pi*2

array([25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13274123,
       25.13274123, 25.13274123, 25.13274123, 25.13274123, 25.13

In [9]:
f = np.empty(25)
f

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609111e-307,
       7.56556349e-307, 7.56599807e-307, 7.56595054e-307, 6.23059386e-307,
       1.60218763e-306, 1.29060871e-306, 9.34593493e-307, 6.23059726e-307,
       6.23060405e-307, 6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
       9.34600963e-307, 1.86921143e-306, 6.23061763e-307, 1.42421160e-306,
       6.23055651e-307, 1.86920057e-306, 1.42410974e-306, 8.34445561e-308,
       3.98356967e-242])

In [10]:
for i in range(len(f)):
    f[i]=i**2
f    

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.,
       121., 144., 169., 196., 225., 256., 289., 324., 361., 400., 441.,
       484., 529., 576.])

In [ ]:
np.empty(1000)

# Why Numpy is useful: 
Memory-efficient container that provides fast numerical operations.

# Looking for something:

In [11]:
import numpy as np
np.lookfor('create array')
#Search results for 'create array'
#---------------------------------



AttributeError: `np.lookfor` was removed in the NumPy 2.0 release. Search NumPy's documentation directly.

In [12]:
np.array(a)
# Create an array.

NameError: name 'a' is not defined

In [ ]:
np.memmap(a)
# Create a memory-map to an array stored in a *binary* file on disk

In [13]:
np.concatenate?


Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...),
    axis=0,
    out=None,
    dtype=None,
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'

In [14]:
np.convolve

<function convolve at 0x000002BCFA584830>

# Creating arrays
#### Manual construction of arrays
##### $\frac{1-D}{}$

In [15]:
a = np.array([0,1,2,3]);a
# Creating an array and assigning it to a variable called 'a'

array([0, 1, 2, 3])

In [16]:
a.ndim
# Check the dimenssions of the array, 'a'

1

In [17]:
a.shape
# Checks the number of elements in each dimenssions

(4,)

In [18]:
len(a)
# Check the number of elements in the array, 'a'

4

## 2-D, 3-D, . . . :

In [23]:
b = np.array([[0,1,2], [3,4,5],[6,7,8]]);b
b.ndim
b.shape
len(b)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]]);c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
c.shape
c.ndim

3

Exercise: Simple arrays

• Create a simple two dimensional array. First, redo the examples from above. And then create
your own: how about odd numbers counting backwards on the first row, and even numbers on
the second?

• Use the functions len(), numpy.shape() on these arrays. How do they relate to each other?
And to the ndim attribute of the arrays?

In [26]:
# The 2-d array
ar = np.array([list(range(9,3,-2)),list(range(10,4,-2))]);ar 



array([[ 9,  7,  5],
       [10,  8,  6]])

In [27]:
# lenght of ar
len(ar)


2

In [28]:
# shape of ar
np.shape(ar);ar.shape

(2, 3)

In [29]:
# Dimensions of ar
ar.ndim

2

In [30]:
np.ones((3,2,3))*15
#np.ones((dimension, nrow, ncol))

array([[[15., 15., 15.],
        [15., 15., 15.]],

       [[15., 15., 15.],
        [15., 15., 15.]],

       [[15., 15., 15.],
        [15., 15., 15.]]])

• np.random: random numbers (Mersenne Twister PRNG):

In [ ]:
 np.random.rand(4) # generating 4 random numbers of uniform distribution

In [ ]:
np.random.randn(4) # Generating 4 random numgers of Guasian 

In [ ]:
np.random.seed(1234) # Setting the random seed

## Exercise: Creating arrays using functions
### • Experiment with arange, linspace, ones, zeros, eye and diag.
### • Create different kinds of arrays with random numbers.
### • Try setting the seed before creating an array with random values.
### • Look at the function np.empty. What does it do? When might this be useful?

In [ ]:
np.arange(1,5,0.1)

In [ ]:
np.linspace(1,5,10)

In [31]:
np.eye(2) # the identity of a matrix

array([[1., 0.],
       [0., 1.]])

In [32]:
np.identity(3) # Alternative for a nxn identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.diag([1,2,3,4,5]) # The diagonals of a matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [35]:
a.dtype

dtype('int64')

In [36]:
a = np.array([1,2,3,4,5,6,7,8]);a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a_rs=a.reshape((4,2))

In [38]:
a.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [39]:
b = a.reshape((2,4))

In [40]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [41]:
np.zeros((4,5),dtype = int)# we have to convert the datatype to int


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
np.zeros(b.shape,b.dtype)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
# we could use
np.zeros_like(b)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
np.ones_like(b)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
a.shape

(8,)

In [46]:
a.size

8

In [47]:
b.shape

(2, 4)

In [48]:
b.size

8

In [49]:
a.reshape((2,2,2)).shape

(2, 2, 2)

In [50]:
a.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
len(b)

2

In [52]:
b.size

8

In [53]:
c = np.arange(16,32)
c

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [54]:
import numpy as np

In [55]:
np.lookfor('create array')

AttributeError: `np.lookfor` was removed in the NumPy 2.0 release. Search NumPy's documentation directly.

# Creating an array

In [56]:
# create a memory map to an array stored in a *binary* file on disk
np.memmap('Map function.ipynb')

memmap([123,  10,  32, ...,  10, 125,  10], shape=(13038,), dtype=uint8)

In [57]:
#np.concatenate?
a=np.array([[1,2,3],[4,5,12]])
b=np.array([[6,7,11],[8,9,10]])
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 6,  7, 11],
       [ 8,  9, 10]])

In [58]:
c=np.array([1,2,3,4])
d=np.array([5,6,7,8])
np.convolve(c,d,mode='full')

array([ 5, 16, 34, 60, 61, 52, 32])

In [59]:
np.convolve?

Signature:       np.convolve(a, v, mode='full')
Call signature:  np.convolve(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function convolve at 0x000002BCFA5813A0>
File:            c:\users\user\.ai-navigator\micromamba\envs\cpu\lib\site-packages\numpy\_core\numeric.py
Docstring:      
Returns the discrete, linear convolution of two one-dimensional sequences.

The convolution operator is often seen in signal processing, where it
models the effect of a linear time-invariant system on a signal [1]_.  In
probability theory, the sum of two independent random variables is
distributed according to the convolution of their individual
distributions.

If `v` is longer than `a`, the arrays are swapped before computation.

Parameters
----------
a : (N,) array_like
    First one-dimensional input array.
v : (M,) array_like
    Second one-dimensional input array.
mode : {'full', 'valid', 'same'}, optional
    'full':
      By default, mode is 'full'.  This returns the

In [61]:
np.conj==np.conjugate

True

In [62]:
f = np.array([0,1,2,3])
f

array([0, 1, 2, 3])

In [63]:
f.ndim

1

In [64]:
f.shape

(4,)

In [65]:
len(f)

4

In [66]:
e = np.array([[[1,2],[3,4],[5,6]]])

In [67]:
len(e)

1

In [68]:
e.ndim

3

In [69]:
e.shape

(1, 3, 2)

# Functions of creating an array with numpy

### Evenly space

In [70]:
a = np.arange(10) # 0 ... n-1
b  = np.arange(1,9,2) # 1...n-1 with steps of 2

a,b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7]))

### Number of points

In [71]:
c = np.linspace(0,1,6) # start, end , num-points
d = np.linspace(0,1,5,endpoint=False)
c,d

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]), array([0. , 0.2, 0.4, 0.6, 0.8]))

### Common arrays

In [72]:
a = np.ones((3,3))
b = np.zeros((2,3))
c = np.eye(3)
d = np.diag(np.array([1,2,3,4]))
a,b,c,d

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]))

### np.random: random numbers (Mersenne Twister PRNG):

In [73]:
a = np.random.rand(4) # Uniform in [ 0,1]
b = np.random.randn(4) #Gaussian
c = np.random.seed(1234) # Setting the seed
a,b,c

(array([0.72313251, 0.44461515, 0.9365228 , 0.68913456]),
 array([-0.53035409, -0.65260986, -1.2552176 ,  1.31071862]),
 None)

### Exercise: Creating arrays using functions
• Experiment with arange, linspace, ones, zeros, eye and diag.

• Create different kinds of arrays with random numbers.

• Try setting the seed before creating an array with random values.

• Look at the function np.empty. What does it do? When might this be useful?
4.1.3

# BASIC DATA TYPE

In [74]:
a = np.array([1,2,3,4,5,6],dtype=int) # Specifying the data type
a.dtype

dtype('int64')

In [75]:
a = np.ones((4,4)) # By default data type is foat
a.dtype

dtype('float64')

In [76]:
d = np.array([1+2j, 3+4j, 5+6j]) # Complex
d.dtype

dtype('complex128')

In [77]:
e = np.array([True,False,False,True]) # Bool
e.dtype

dtype('bool')

In [78]:
f = np.array(['Bonjour', 'hello', 'Hallo']) #String
# String withat most 7 7 letters
f.dtype

dtype('<U7')

$$f(x)=\frac{\beta^{\alpha}}{\Gamma(\alpha)}X^{\alpha-1}\exp^{-x\beta}$$

$$cf0$$

$$pv = \sum_{t=1}^{t=n}\frac{cf_{t}}{(1+i)^{time_{t}}}$$

$$k_e = \frac{d_0(1+g)}{P_0}+g$$