# WHILE LOOP

In [1]:
##############################################################################################################################
############                                  while loop                                                          ############
##############################################################################################################################

In [1]:
# syntax
# declaclaration of varaiable
# while(condition):
a=2
while(a<10):
    print(a%2)
    a += 1

0
1
0
1
0
1
0
1


In [2]:
range(10) # st0p at 10

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
print(range(1,8))

range(1, 8)


In [10]:
list(range(5,-9,-2))
# If stop is less than start, step must be positive else ot will return none

[5, 3, 1, -1, -3, -5, -7]

In [6]:
list(range(2,-25,-5))
# If stop is less than start, step must be positive else ot will return none

[2, -3, -8, -13, -18, -23]

In [11]:
list(range(2,-25,-5.0)) 
# There is error because the arguments of the range function is integer

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
#a = [-2.5,-2.75,-3.0,-3.5,-3.75,-4.0]



In [12]:
# We want to reproduce the list above using range
# The max is -2.5 and te least is -4.0 and step is -0.25
# In order to make it feasible, we multiply through by 100
# Then we insert into the empty list a, by dividing each of them ny 100
a=[]
for i in range(-250,-420,-25):
    a.append(i/100)
a

[-2.5, -2.75, -3.0, -3.25, -3.5, -3.75, -4.0]

$Conside\r the\ function\ g(x)\ =\ x^2\ and\ f(x)\ =\ 2x-1\ on\ \left[-2,5\right]\ \ \ $
$write\ a\ code\ to\ approximate\ the\ max\ distance\ between\ the\ two\ functions$

In [14]:
a = []
def g(x):
    return(x**2)       
def f(x):
    return(2*x-1)
for x in range(-2,6):
    a.append(abs(g(x)-f(x)))
print(a)
max(a)

[9, 4, 1, 0, 1, 4, 9, 16]


16

In [15]:
# A single function to find the maximum
def maximum(x):
    d =[]
    for i in range(len(x)):
        d.append(abs((x[i]**2)-(x[i]*2-1)))
    return max(d)

In [18]:
assert maximum((1,2,3))==4

In [19]:
assert maximum(range(-2,6))==16

$Consider\ a\ sequence\ defined\ by\ an=(1+1/n)^n.$
$show\ that\ the\ sequence\ is\ convergent\ as\ n\ approaches\ infinity\ (\infty)$
$and\ find\ an\ approximation\ of\ the\ value\ it\ converges\ to$

In [22]:
seq = []
def convergence(n):
  an = ((1 + 1/n)**n)
  return(an) 

  for n in range(1,10000000):
     seq.append(an)
     print(seq)

In [38]:
convergence(10000000000000)

2.716110034086901

### Assuming on day one a man is given 9ghp and the amount is doubled everyday.
### After how many days will the amount be greater tahn ghc 10,000

In [60]:
amount = 0.09
days = 1
Amount = [0.09]
while(amount < 10000):
    amount = amount*2
    a=print('After ', days+1, '  Days,   The   Amount   is   GHS', round(amount,2))
    days += 1

After  2   Days,   The   Amount   is   GHS 0.18
After  3   Days,   The   Amount   is   GHS 0.36
After  4   Days,   The   Amount   is   GHS 0.72
After  5   Days,   The   Amount   is   GHS 1.44
After  6   Days,   The   Amount   is   GHS 2.88
After  7   Days,   The   Amount   is   GHS 5.76
After  8   Days,   The   Amount   is   GHS 11.52
After  9   Days,   The   Amount   is   GHS 23.04
After  10   Days,   The   Amount   is   GHS 46.08
After  11   Days,   The   Amount   is   GHS 92.16
After  12   Days,   The   Amount   is   GHS 184.32
After  13   Days,   The   Amount   is   GHS 368.64
After  14   Days,   The   Amount   is   GHS 737.28
After  15   Days,   The   Amount   is   GHS 1474.56
After  16   Days,   The   Amount   is   GHS 2949.12
After  17   Days,   The   Amount   is   GHS 5898.24
After  18   Days,   The   Amount   is   GHS 11796.48


In [61]:
from math import log
def nth_position(an,a,r):
    n = ((log(an) - log(a))/(log(r))) + 1
    return (n)

In [62]:
nth_position(10000,0.09,2)

17.761643567881862

In [63]:
# nth term of a geometric series
def nth_term(a,r,n):
    an = a*r**(n-1)
    return(an)

#nth_term(0.09,2,16)
amount=[]
for x in range(1,19):
    y = (nth_term(0.09,2,x))
    
    amount.append(y)
amount   

[0.09,
 0.18,
 0.36,
 0.72,
 1.44,
 2.88,
 5.76,
 11.52,
 23.04,
 46.08,
 92.16,
 184.32,
 368.64,
 737.28,
 1474.56,
 2949.12,
 5898.24,
 11796.48]

In [64]:
import numpy as np

In [65]:
A=np.arange(0,4,.25);A

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75])

In [66]:
np.zeros_like(A)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.ones_like(A)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
6*np.empty_like(A)

array([36., 36., 36., 36., 36., 36., 36., 36., 36., 36., 36., 36., 36.,
       36., 36., 36.])