In [1]:
phrase = "Hello world"

In [2]:
phrase

'Hello world'

In [3]:
print(phrase)

Hello world


In [4]:
type(phrase)

str

In [22]:
text = "She Said,'What time is it ?'"

In [23]:
text

"She Said,'What time is it ?'"

In [24]:
print(text)

She Said,'What time is it ?'


In [7]:
prompt = "Hey, what's up? "
user_input = input(prompt)
print("You said:", user_input)

Hey, what's up? es
You said: es


In [8]:
prompt="what is your nmae? "
name = input(prompt)
prompt1="where do you school? "
school = input(prompt1)
print('your name is ', name.upper(), 'And you are a student of ', school.upper())

what is your nmae? d
where do you school? fg
your name is  D And you are a student of  FG


In [25]:
0.1 + 0.2

0.30000000000000004

In [41]:
0.1+0.

0.1

In [10]:
import numpy as np

In [11]:
c = np.linspace(0,1.1,12)
c

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [12]:
c.reshape((2,6))

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. , 1.1]])

In [13]:
c.reshape((-1,3))

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8],
       [0.9, 1. , 1.1]])

In [14]:
c.reshape((3,-1))

array([[0. , 0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6, 0.7],
       [0.8, 0.9, 1. , 1.1]])

In [15]:
x = np.linspace(0,1,11)

In [16]:
np.sin(x)

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
       0.84147098])

In [17]:
x**2 + 2*x +1

array([1.  , 1.21, 1.44, 1.69, 1.96, 2.25, 2.56, 2.89, 3.24, 3.61, 4.  ])

In [18]:
b=np.copy(x)
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [42]:
e = x

In [43]:
e is x

True