In [2]:
from numpy import isclose

In [3]:
isclose([1,2,3],[2,2,3])

array([False,  True,  True])

In [1]:
import numpy as np

def arclength(f,a,b,n):
    x = np.linspace(a,b,n+1)
    y = f(x)
    dx = x[1]-x[0]
    dy = y[1]-y[0]
    L = np.sqrt(dx**2 + dy**2)
    for i in range(1,n):
        dx = x[i+1]-x[i]
        dy = y[i+1]-y[i]
        L += np.sqrt(dx**2 + dy**2)
    return L

In [8]:
assert isclose(arclength(lambda x: x**2,1,3,100001),8.268145901058078)

In [9]:
arclength(lambda x: x**2,1,3,100001)

8.268145901060883

In [10]:
import numpy as np

def arclength(f,a,b,n):
     # YOUR CODE HERE
    x = np.linspace(a,b,n+1)
    y = f(x)
    dx = x[1]-x[0]
    dy = y[1]-y[0]
    L = np.sqrt(dx**2 + dy**2)
    for i in range(1,n):
        dx = x[i+1]-x[i]
        dy = y[i+1]-y[i]
        L += np.sqrt(dx**2 + dy**2)
    return L
    raise NotImplementedError()

In [11]:
assert isclose(arclength(lambda x: x**2,1,3,100001),8.268145901058078)

In [12]:
assert isclose(arclength(lambda x: x**0.5,1,3,1001),2.1325089836938407)

In [13]:
assert isclose(arclength(lambda x: 5*x-2,-2,3,1001),25.49509756796383)

In [14]:
assert isclose(arclength(lambda x: x**2,1,3,100001),8.268145901058078)

In [4]:
import numpy as np

def erf(x,n):
    # YOUR CODE HERE
    deltax = x/n
    xi = np.linspace(0,x,n+1)
    fxi = np.exp(-xi**2)
    return 2/np.sqrt(np.pi)*np.sum(fxi[:-1]*deltax)
    raise NotImplementedError()

In [5]:
assert isclose(erf(1,1001),0.8430570034585734)

In [6]:
assert isclose(erf(-5,101),-1.0279301774013976)

In [7]:
assert isclose(erf(100,501),1.1126126913268979)

In [19]:
def isDecreasing(x):
    # YOUR CODE HERE
    for i in range(len(x) - 1):
        if x[i] <= x[i + 1]:
            return False
    return True
    raise NotImplementedError()

In [20]:
assert isDecreasing([9,3,0,-2,-9,-15]) == True

In [21]:
assert isDecreasing([9,3,0,-2,-2,-15]) == False

In [22]:
assert isDecreasing([9,3,0,-2,3,-15]) == False

In [2]:
from googlesearch import search

SyntaxError: invalid syntax (1511378596.py, line 1)

# $$f(x)=2x^3+5x^2-10x+12 😎$$ 

$\sqrt{x}$

$tf_{ij}^|=tf_{ij}\log(m)$

In [1]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [7]:
def unity(n):
    from cmath import sin, cos,pi
    return [cos((2*k*pi)/n)+1j*sin((2*k*pi)/n) for k in range(n)]

In [8]:
unity(100000)

[(1+0j),
 (0.9999999980260791+6.283185303045416e-05j),
 (0.9999999921043164+0.0001256637058128581j),
 (0.9999999822347121+0.00018849555809916164j),
 (0.9999999684172661+0.0002513274096413145j),
 (0.9999999506519784+0.00031415926019126653j),
 (0.9999999289388491+0.00037699110950096756j),
 (0.9999999032778785+0.0004398229573223673j),
 (0.9999998736690663+0.0005026548034074155j),
 (0.9999998401124129+0.0005654866475080623j),
 (0.9999998026079184+0.0006283184893762572j),
 (0.999999761155583+0.0006911503287639501j),
 (0.9999997157554067+0.000753982165423091j),
 (0.9999996664073898+0.0008168139991056295j),
 (0.9999996131115324+0.0008796458295635155j),
 (0.9999995558678348+0.0009424776565486989j),
 (0.9999994946762972+0.0010053094798131298j),
 (0.9999994295369199+0.0010681412991087583j),
 (0.999999360449703+0.0011309731141875335j),
 (0.9999992874146468+0.001193804924801406j),
 (0.9999992104317518+0.0012566367307023255j),
 (0.9999991295010181+0.001319468531642242j),
 (0.9999990446224462+0.0013

In [1]:
import numpy as np

In [5]:
np.arange(0,4,.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75])

In [20]:
c = np.linspace(0,1.1,12)
c

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

In [27]:
c = c.reshape((3,-1)) # The specified number of rows and the rest for column
c

array([[0. , 0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6, 0.7],
       [0.8, 0.9, 1. , 1.1]])

In [9]:
c.shape

(4, 3)

In [11]:
print(c.dtype)

float64


In [8]:
c = c.reshape((4,3))
c

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8],
       [0.9, 1. , 1.1]])

In [33]:
c = c.reshape((-1,6)).astype(complex)
c
int(c)

TypeError: only size-1 arrays can be converted to Python scalars

In [32]:
c.astype('int')

C:\Users\user\AppData\Local\Temp\ipykernel_20192\1158464241.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  c.astype('int')


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1]])

In [34]:
c.shape

(2, 6)

In [35]:
c.size

12

In [36]:
c.ndim

2

In [43]:
c + np.array([1,2]).reshape(2,1)

array([[1. +0.j, 1.1+0.j, 1.2+0.j, 1.3+0.j, 1.4+0.j, 1.5+0.j],
       [2.6+0.j, 2.7+0.j, 2.8+0.j, 2.9+0.j, 3. +0.j, 3.1+0.j]])

In [44]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
a = 2*np.eye(4)
b = np.array([1,2,3,4])
c = b.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [55]:
np.dot(b,a)

array([2., 4., 6., 8.])

In [56]:
np.dot(a,c)

array([[2.],
       [4.],
       [6.],
       [8.]])

In [60]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [61]:
%matplotlib backend

KeyError: 'backend'

$$\sigma$$

$$\sum_{x=1}^{\infty} \chi^2 + 2 f(x)$$

In [1]:
import requests

# Define the API endpoint URL
url = 'https://api.semanticscholar.org/graph/v1/paper/search'

# More specific query parameter
query_params = {'query': 'quantum computing'}

# Directly define the API key (Reminder: Securely handle API keys in production environments)
api_key = 'your api key goes here'  # Replace with the actual API key

# Define headers with API key
headers = {'x-api-key': api_key}

# Send the API request
response = requests.get(url, params=query_params, headers=headers)

# Check response status
if response.status_code == 200:
   response_data = response.json()
   # Process and print the response data as needed
   print(response_data)
else:
   print(f"Request failed with status code {response.status_code}: {response.text}")

ModuleNotFoundError: No module named 'requests'